alter table booking_comments add column if not exists parent_id bigint references booking_comments(id) on delete cascade;

create table if not exists booking_comment_reactions (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references booking_comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  unique (comment_id, user_id, emoji)
);

alter table booking_comment_reactions enable row level security;

create policy "Owners can view reactions on their booking comments" on booking_comment_reactions
  for select using (
    exists (
      select 1 from booking_comments c
      join bookings b on b.id = c.booking_id
      join calendar_events e on e.id = b.event_id
      where c.id = booking_comment_reactions.comment_id and e.user_id = auth.uid()
    )
  );

create policy "Owners can add reactions to their booking comments" on booking_comment_reactions
  for insert with check (
    user_id = auth.uid()
    and exists (
      select 1 from booking_comments c
      join bookings b on b.id = c.booking_id
      join calendar_events e on e.id = b.event_id
      where c.id = booking_comment_reactions.comment_id and e.user_id = auth.uid()
    )
  );

create policy "Owners can remove their own reactions" on booking_comment_reactions
  for delete using (user_id = auth.uid());

notify pgrst, 'reload schema';
