create table if not exists booking_comments (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references bookings(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now()
);

alter table booking_comments enable row level security;

create policy "Owners can view their booking comments" on booking_comments
  for select using (
    exists (
      select 1 from bookings b
      join calendar_events e on e.id = b.event_id
      where b.id = booking_comments.booking_id and e.user_id = auth.uid()
    )
  );

create policy "Owners can add comments to their bookings" on booking_comments
  for insert with check (
    user_id = auth.uid()
    and exists (
      select 1 from bookings b
      join calendar_events e on e.id = b.event_id
      where b.id = booking_comments.booking_id and e.user_id = auth.uid()
    )
  );

notify pgrst, 'reload schema';
