-- Shared inboxes/channels shown under "Shared" in the inbox sidebar.
create table if not exists inbox_channels (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  icon_color text not null default '#7C3AED',
  created_at timestamptz not null default now()
);

-- Conversations are the top-level inbox threads.
create table if not exists inbox_conversations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  channel_id bigint references inbox_channels(id) on delete set null,
  subject text not null,
  status text not null default 'open' check (status in ('open', 'later', 'done', 'trash', 'spam')),
  kind text not null default 'message' check (kind in ('message', 'task', 'discussion')),
  direction text not null default 'inbound' check (direction in ('inbound', 'outbound')),
  is_draft boolean not null default false,
  sender_name text,
  sender_initials text,
  sender_avatar_color text not null default '#7C3AED',
  assignee_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Messages within a conversation, including internal-only comments.
create table if not exists inbox_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references inbox_conversations(id) on delete cascade,
  author_user_id uuid references auth.users(id) on delete set null,
  author_name text,
  body text not null,
  is_internal_comment boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists inbox_tags (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  color text not null default '#7C3AED'
);

create table if not exists inbox_conversation_tags (
  conversation_id bigint not null references inbox_conversations(id) on delete cascade,
  tag_id bigint not null references inbox_tags(id) on delete cascade,
  primary key (conversation_id, tag_id)
);

create table if not exists inbox_conversation_subscribers (
  conversation_id bigint not null references inbox_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  primary key (conversation_id, user_id)
);

alter table inbox_channels enable row level security;
alter table inbox_conversations enable row level security;
alter table inbox_messages enable row level security;
alter table inbox_tags enable row level security;
alter table inbox_conversation_tags enable row level security;
alter table inbox_conversation_subscribers enable row level security;

create policy "Owners manage their channels" on inbox_channels
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "Owners manage their conversations" on inbox_conversations
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "Owners manage messages on their conversations" on inbox_messages
  for all using (
    exists (select 1 from inbox_conversations c where c.id = inbox_messages.conversation_id and c.user_id = auth.uid())
  ) with check (
    exists (select 1 from inbox_conversations c where c.id = inbox_messages.conversation_id and c.user_id = auth.uid())
  );

create policy "Owners manage their tags" on inbox_tags
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "Owners manage tags on their conversations" on inbox_conversation_tags
  for all using (
    exists (select 1 from inbox_conversations c where c.id = inbox_conversation_tags.conversation_id and c.user_id = auth.uid())
  ) with check (
    exists (select 1 from inbox_conversations c where c.id = inbox_conversation_tags.conversation_id and c.user_id = auth.uid())
  );

create policy "Owners manage subscribers on their conversations" on inbox_conversation_subscribers
  for all using (
    exists (select 1 from inbox_conversations c where c.id = inbox_conversation_subscribers.conversation_id and c.user_id = auth.uid())
  ) with check (
    exists (select 1 from inbox_conversations c where c.id = inbox_conversation_subscribers.conversation_id and c.user_id = auth.uid())
  );

notify pgrst, 'reload schema';
